demo
made-ml-in-prod-2022/dertty pull request #1
Opened 2022-05-16 11:57 UTC by dertty

Основные архитектурные и тактические решения:
1. Pipenv - разрешение зависимостей, dev -  среда, чтобы не раздувать pro venv,
2. Шаблон Cookiecutter Data Science - понятный и стандартизированный шабон проекта и набор иструментов.
3. Makefile для основных команд
4. Проект построен на конфигах

Проект создан на оснвое шаблона Cookiecutter Data Science - откуда было удалено всё, что не используется. С помощью make запускаются пайплайны обработки данных, обучения и предикта.

Самооценка:
- [x] В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание того, что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код (1 балл)
- [x] В пулл-реквесте проведена самооценка, распишите по каждому пункту выполнен ли критерий или нет и на сколько баллов(частично или полностью) (1 балл)
- [x] Выполнено EDA, закоммитьте ноутбук в папку с ноутбуками (1 балл) Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы) -  проведён анализ данных в notebooks/eda.ipynb
- [x] Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл) - make eda генерирует отчёт с помощью pandas profiling  и сохраняет его в reports/ в виде html и json. 
- [x] Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкцию по запуску (3 балла) - в readme описаны команды make data, make train
- [x] Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme (3 балла) - make predict
- [x] Проект имеет модульную структуру (2 балла)
- [x] Использованы логгеры (2 балла) - логов мало, только самое важное, но и действий немного
- [ ] Написаны тесты на отдельные модули и на прогон обучения и predict (3 балла) - не сделал
- [x] Для тестов генерируются синтетические данные, приближенные к реальным (2 балла) - можно посмотреть на библиотеки https://faker.readthedocs.io/, https://feature-forge.readthedocs.io/en/latest/, можно просто руками посоздавать данных, собственноручно написанными функциями. - для трансформеров написана тесты, где используется fake
- [x] Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла) - два примитивных конфета для двух моделей: logreg.yaml и tree.yaml
- [x] Используются датаклассы для сущностей из конфига, а не голые dict (2 балла) - используется omegadict
- [x] Напишите кастомный трансформер и протестируйте его (3 балла) https://towardsdatascience.com/pipelines-custom-transformers-in-scikit-learn-the-step-by-step-guide-with-python-code-4a7d9b068156 - сделано два кастомных трансформера MultiOneHotEncoder и FeatureSelection - для MultiOneHotEncoder написан простой тест (отчасти бесполезный)
- [x] В проекте зафиксированы все зависимости (1 балл) -  pipenv -> requirements.txt
- [ ] Настроен CI для прогона тестов, линтера на основе github actions (3 балла). Пример с пары: https://github.com/demo-ml-cicd/ml-python-package
- [x] Используйте hydra для конфигурирования (https://hydra.cc/docs/intro/) - 3 балла. - src/configs

2022-05-29 18:37 UTC, nickdndev requested changes
1. Добавить проверку в трасформере
2. не нашел где создается датасет для тестов

2022-05-29 18:37 UTC, nickdndev commented on ml_project/src/models/predict_model.py
> +    print()
remove

2022-05-29 18:37 UTC, nickdndev commented on ml_project/src/models/transformers.py
> +        data = []
add validation fit or not transformer 
![image](https://user-images.githubusercontent.com/49230518/170886116-a6df80dd-234f-4cc2-9409-b46fab81b2de.png)

2022-07-18 12:22 UTC, dertty commented on ml_project/src/models/predict_model.py
> +    print()
Удалил

2022-07-18 12:39 UTC, dertty commented on ml_project/src/models/transformers.py
> +        data = []
Добавил

2022-07-18 13:13 UTC, dertty commented
Датасет для тестов не создавался отдельно.
Предполагалось, что данные для обучения и для тестов кладутся в data/raw, затем train и test  прогоняются через src/data/make_dataset.py filename=....  А затем в трейн и predict передаются нужные файлы.
Но добавил train_test_split в пайлайн.
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/4625504/179518885-f789a873-aa6e-4b3b-af16-d4884a054ad3.png">

2022-07-19 12:25 UTC, nickdndev commented
score : 28

2022-07-19 12:26 UTC, nickdndev approved these changes

2022-07-19 12:47 UTC, merged